backend:
  name: git-gateway
  branch: master


  media_folder: "static/uploads"
  public_folder: "uploads"

  collections:
    - name: "antrenman"
      label: "Antrenman"
      folder: "content/antrenman"
      create: false
      slug: "{{year}}-{{month}}-{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string", required: true}